config/routes.rb
Rails.application.routes.draw do
  get 'login' => "users#login_form"
  post 'login' => "users#login"
  get 'logout' => "users#logout"
  
  get 'signup' => "users#new"
  post 'users/:id/update' => "users#update"
  get 'users/:id/edit' => "users#edit"
  post 'users/create' => "users#create"
  # get 'users/index' => "users#index"
  get 'users/:id' => "users#show",as: :user
  
  get 'posts/top' => "posts#top"
  # get 'posts/index' => "posts#index"
  # get 'posts/new' => "posts#new"
  # get 'posts/:id' => "posts#show"
  # post 'posts/create' => "posts#create"
  # get 'posts/:id/edit' => "posts#edit"
  # post 'posts/:id/update' => "posts#update"
  # post 'posts/:id/destroy' => "posts#destroy"

  get 'shops/index/:shop_category_id' => "shops#index"
  get 'shops/:shop_id' => "shops#show", as: :shop
  get 'shops/:shop_id/posts' => "posts#index",as: :shop_posts
  get 'shops/:shop_id/posts/new' => "posts#new", as: :new_comment
  post 'shops/:shop_id/posts/new' => "posts#create"
  get  'shops/:shop_id/posts/:post_id' => "posts#show",as: :shop_post
  get  'shops/:shop_id/posts/:post_id/edit' =>  "posts#edit",as: :edit_shop_post
  post 'shops/:shop_id/posts/:post_id/update' => "posts#update"
  post 'shops/:shop_id/posts/:post_id/destroy' => "posts#destroy",as: :destroy_shop_post

  
  get '/' => "home#top"
  get 'about' => "home#about"

  get 'favorites/index' => "favorites_shops#index"
  
  resources :posts do
    resource :favorites_post, only: [:create, :destroy]
  end

  resources :shops do
    resource :favorites_shop, only: [:create]
  end
 

end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :posts
  has_many :users
  has_many :favorite_post, dependent: :destroy
  has_many :favorites, dependent: :destroy
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
   before_action :authenticate_user, { only: [:index, :edit, :update] }
  
   def index
    @user = @current_user
    @shops = Shop.where(shop_category_id: params[:shop_category_id])
    @shop = Favorite.where(user_id: @user).exists?
end

  def show
    @id = params[:shop_id]
    @path = "/shops/#{@id}/posts"
    @path2 = "/shops/#{@id}/posts/new"
    @shops = Shop.find_by(id: params[:shop_id])
    @posts = Post.where(shop_id: params[:shop_id])
    @posts = @posts.order(updated_at: :desc).limit(2)

    @post = Favorite.where(user_id: @user).exists?
 
    @users = @current_user

    @average_shop_posts = @posts.average(:rate).to_f.round(1)
  end
end 

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/index.html.erb
<div class="main shops-index">
<div class="container">
<main>
<div class="wrapper">
<h1 class="sec-title">店舗一覧</h1>
<section id="news" class="wrapper">
<table>
<% @shops.each do |shop| %>
<tr>
<td><%= image_tag shop.shop_photo,width: "90px", height: "70px"  %></td>
<td style="text-align :center;"><%= link_to(shop.name,"/shops/#{shop.id}") %></td>
<td><%= shop.access %></td>
  <td><%= form_tag(shop_favorites_shop_path(shop.id)) do %>
    <input type="hidden" name="shop_id" value="#{shop.id}">
    <input type="submit" value="検討">
    <% end %></td>
     <% end %>
    </tr>
</table>
</div>
</section>
   </div>
  </div>
 </main>

app/views/shops/show.html.erb
<div class="main shops-show">
<div class="container">
<main>
<h1 class="sec-title"><%= @shops.name %></h1>
<section id="shopinfo" class="wrapper">
<td><%= image_tag @shops.shop_photo,width: "500px", height: "300px" %></td>
<table>
<tr>
<td>住所：</td><td><%= @shops.address %></td>
</tr>
<tr>
<td>アクセス：</td><td><%= @shops.access %></td></tr>
<tr>
<td>電話番号：</td><td><%= @shops.phone_number %></td></tr>
<tr>
<td>店舗評価：</td><td><%= @average_shop_posts %></td></tr>
</table>
</section>
<section id="info" class="wrapper">
<h2 class="sec-title">みんなの口コミ</h2>
<% @posts.each do |post| %>
<table>
<tr>
<td style="text-align: center;">ユーザー:<%= post.user.name %></td>
<td style= "width:350px;"><%= post.content%></td>
</tr>

</table>
<div class=like >
<table>
<% if @post %>
   <%= link_to post_favorites_post_path(post.id), method: :delete do %>
    <td><input type="submit" value="❤️">
   <% end %>
<% else %>
<% if @users!= nil %>
  <%= form_tag(post_favorites_post_path(post.id)) do %>
    <input type="hidden" name="post_id" value="#{post.id}">
 <input type="submit" value="❤️"></td>
 <% end %>
<%= post.favorite_posts.count %>
    <% end %>
   <% end %>
 <% end %> 
 </div>
 </section>
 <p id="button">
<%= link_to @path do%><button>口コミ一覧</button>
    <% end %>
<%= link_to @path2 do %><button>口コミ追加</button>
   <% end %>
  </main>
 </div>
</div>

    