config/routes.rb
Rails.application.routes.draw do
  get 'login' => "users#login_form"
  post 'login' => "users#login"
  get 'logout' => "users#logout"
  
  get 'signup' => "users#new"
  post 'users/:id/update' => "users#update"
  get 'users/:id/edit' => "users#edit"
  post 'users/create' => "users#create"
  # get 'users/index' => "users#index"
  get 'users/:id' => "users#show",as: :user
  
  get 'posts/top' => "posts#top"
  # get 'posts/index' => "posts#index"
  # get 'posts/new' => "posts#new"
  # get 'posts/:id' => "posts#show"
  # post 'posts/create' => "posts#create"
  # get 'posts/:id/edit' => "posts#edit"
  # post 'posts/:id/update' => "posts#update"
  # post 'posts/:id/destroy' => "posts#destroy"

  get 'shops/index/:shop_category_id' => "shops#index"
  get 'shops/:shop_id' => "shops#show", as: :shop
  get 'shops/:shop_id/posts' => "posts#index",as: :shop_posts
  get 'shops/:shop_id/posts/new' => "posts#new", as: :new_comment
  post 'shops/:shop_id/posts/new' => "posts#create"
  get  'shops/:shop_id/posts/:post_id' => "posts#show",as: :shop_post
  get  'shops/:shop_id/posts/:post_id/edit' =>  "posts#edit",as: :edit_shop_post
  post 'shops/:shop_id/posts/:post_id/update' => "posts#update"
  post 'shops/:shop_id/posts/:post_id/destroy' => "posts#destroy",as: :destroy_shop_post

  
  get '/' => "home#top"
  get 'about' => "home#about"

  get 'favorites/index' => "favorites_shops#index"
  
  resources :posts do
    resource :favorites_post, only: [:create, :destroy]
  end

  resources :shops do
    resource :favorites_shop, only: [:create]
  end
 

end

app/models/user.rb
class User < ApplicationRecord
  validates :name, { presence: true }
  validates :email, { presence: true, uniqueness: true }
  validates :password, { presence: true }
  has_many :shops, dependent: :destroy
  has_many :favorites_post, dependent: :destroy
  has_many :favorites, dependent: :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, { only: [:index, :show, :edit, :update] }
  before_action :forbid_login_user, { only: [:new, :create, :login_form, :login] }
  before_action :ensure_correct_user, { only: [:edit, :update] }

  
  def show
    @user = User.find_by(id: params[:id])
    @post = Post.where(user_id: @user.id)
    @shop = Shop.find_by(id: params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(
      name: params[:name],
      email: params[:email],
      password: params[:password]
    )
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = 'ユーザー登録が完了しました'
      redirect_to("/users/#{@user.id}")
    else
      render('users/new')
    end
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def update
    @user = User.find_by(id: params[:id])
    @user.name = params[:name]
    @user.email = params[:email]

    if params[:image]
      @user.image_name = "#{@user.id}.jpg"
      image = params[:image]
      File.binwrite("public/user_images/#{@user.image_name}", image.read)
    end

    if @user.save
      flash[:notice] = 'ユーザー情報を編集しました'
      redirect_to("/users/#{@user.id}")
    else
      render('users/edit')
    end
  end

  def login_form
  end

  def login
    @user = User.find_by(email: params[:email], password: params[:password])
    if @user
      session[:user_id] = @user.id
      flash[:notice] = 'ログインしました'
      redirect_to user_path(id: @user.id)
    else
      @error_message = 'メールアドレスまたはパスワードが間違っています'
      @email = params[:email]
      @password = params[:password]
      render('users/login_form')
    end
  end

  def logout 
    session[:user_id] = nil 
    flash[:notice] = 'ログアウトしました' 
    redirect_to("/posts/top", allow_other_host: true) 
  end

  def ensure_correct_user
    return unless @current_user.id != params[:id].to_i

    flash[:notice] = '権限がありません'
    redirect_to('users/login_form')
  end
end

app/views/users/edit.html.erb
<div class="main users-edit">
  <div class="container">
    <div class="form-heading">ユーザー情報の編集</div>
    <div class="form users-form">
      <div class="form-body">
      <% @user.errors.full_messages.each do |message| %>
        <div class="form-error">
        <%= message %>
         </div>
        <% end %>

        <%= form_tag("/users/#{@user.id}/update") do %>
        <p>Name</p>
        <input name="name" value="<%= @user.name %>">
        <p>E-mail</p>
        <input name="email" value="<%= @user.email %>">
        <input type="submit" value="保存">
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/login_form.html.erb
<div class="main users-new">
  <div class="container">
    <div class="form-heading">ログイン</div>
    <div class="form users-form">
      <div class="form-body">
      <% if @error_message %>
          <div class="form-error">
            <%= @error_message %>
          </div>
        <% end %>
      <%= form_tag("/login") do %>
        <p>E-mail</p>
        <input name="email" value="<%= @email %>">
        <p>Password</p>
        <input type="password" name="password" value="<%= @password %>">
        <input type="submit" value="ログイン">
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="main users-new">
  <div class="container">
    <div class="form-heading">新規登録</div>
    <div class="form users-form">
      <div class="form-body">
      <% @user.errors.full_messages.each do |message| %>
        <div class="form-error">
        <%= message %>
        </div>
        <% end %>

      <%= form_tag("/users/create") do %>
          <p>Name</p>
          <input name="name" value="<%= @user.name %>">
          <p>E-mail</p>
          <input name="email" value="<%= @user.email %>">
          <p>Password</p>
          <input type="password" name="password" value="<%= @user.password %>">
          <input type="submit" value="新規登録">
      <% end %>
     </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="main user-show">
  <div class="container">
  <main>
  <div class="wrapper">
  <h1 class="sec-title">My page</h1>
  <section id="news" class="wrapper">
  <table style="width :60%;">
  <tr><td style="text-align :center;">
      Name：<%= @user.name %></td></tr>
      <td style="text-align :center;">E-mail：<%= @user.email  %></td>
      <% if @user.id == @current_user.id %>
      <tr><td style="text-align :center;"><button>
      <%= link_to("プロフィールを編集","/users/#{@user.id}/edit") %></button></td></tr>
      </table></section>
      <section id="news" class="wrapper">
    <h3 class="sec-title">過去の投稿</h3>
    <table><tr>
    <% @post.each do |post| %>
    <td style= "margin :0 20px 0 0;"><%= post.shop.name %></td>
    <td><%= truncate(post.content, length: 15) %></td>
    <td><button class= "edit">
    <%= link_to "編集",edit_shop_post_path(post_id:post.id, shop_id:@shop.id) %></button></td>
      </tr>
     <% end %>
     </table>
    <p id="button">    
    <%= link_to("/favorites/index") do%>
      <button>My検討リスト</button>
       </p>
      <% end %>
      <% end %>
    </div>
  </div>
  